//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GrpcCall) DeepCopyInto(out *GrpcCall) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GrpcCall.
func (in *GrpcCall) DeepCopy() *GrpcCall {
	if in == nil {
		return nil
	}
	out := new(GrpcCall)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GrpcCall) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GrpcCallList) DeepCopyInto(out *GrpcCallList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GrpcCall, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GrpcCallList.
func (in *GrpcCallList) DeepCopy() *GrpcCallList {
	if in == nil {
		return nil
	}
	out := new(GrpcCallList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GrpcCallList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GrpcCallObservation) DeepCopyInto(out *GrpcCallObservation) {
	*out = *in
	if in.ResponseData != nil {
		in, out := &in.ResponseData, &out.ResponseData
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.LastCallTime != nil {
		in, out := &in.LastCallTime, &out.LastCallTime
		*out = (*in).DeepCopy()
	}
	if in.CallCount != nil {
		in, out := &in.CallCount, &out.CallCount
		*out = new(int64)
		**out = **in
	}
	if in.ResponseHeaders != nil {
		in, out := &in.ResponseHeaders, &out.ResponseHeaders
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GrpcCallObservation.
func (in *GrpcCallObservation) DeepCopy() *GrpcCallObservation {
	if in == nil {
		return nil
	}
	out := new(GrpcCallObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GrpcCallParameters) DeepCopyInto(out *GrpcCallParameters) {
	*out = *in
	in.RequestData.DeepCopyInto(&out.RequestData)
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GrpcCallParameters.
func (in *GrpcCallParameters) DeepCopy() *GrpcCallParameters {
	if in == nil {
		return nil
	}
	out := new(GrpcCallParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GrpcCallSpec) DeepCopyInto(out *GrpcCallSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GrpcCallSpec.
func (in *GrpcCallSpec) DeepCopy() *GrpcCallSpec {
	if in == nil {
		return nil
	}
	out := new(GrpcCallSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GrpcCallStatus) DeepCopyInto(out *GrpcCallStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GrpcCallStatus.
func (in *GrpcCallStatus) DeepCopy() *GrpcCallStatus {
	if in == nil {
		return nil
	}
	out := new(GrpcCallStatus)
	in.DeepCopyInto(out)
	return out
}
